server:
  port: 31212
spring:
  datasource:
    url: jdbc:clickhouse://1.15.66.155:8123?socket_timeout=300000&dataTransferTimeout=300000
    username: data_manager
    password: mHU8DkAFas3fRZ
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    hikari:
      connection-timeout: 30000
    druid:
      validation-query: select 1
      test-on-borrow: false
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  mvc:
    async:
      request-timeout: 5000000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  kafka:
    servers: 123.60.137.200:9201
    bootstrap-servers: 123.60.137.200:9201
    clientId: client1
    client-id: client1
    producer:
      # 发生错误后，消息重发的次数。
      retries: 0
      #当有多个消息需要被发送到同一个分区时，生产者会把它们放在同一个批次里。该参数指定了一个批次可以使用的内存大小，按照字节数计算。
      batch-size: 16384
      # 设置生产者内存缓冲区的大小。
      buffer-memory: 33554432
      # 键的序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 值的序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # acks=0 ： 生产者在成功写入消息之前不会等待任何来自服务器的响应。
      # acks=1 ： 只要集群的首领节点收到消息，生产者就会收到一个来自服务器成功响应。
      # acks=all ：只有当所有参与复制的节点全部收到消息时，生产者才会收到一个来自服务器的成功响应。
      acks: 1
    consumer:
      # 自动提交的时间间隔 在spring boot 2.X 版本中这里采用的是值的类型为Duration 需要符合特定的格式，如1S,1M,2H,5D
      auto-commit-interval: 1S
      # 该属性指定了消费者在读取一个没有偏移量的分区或者偏移量无效的情况下该作何处理：
      # latest（默认值）在偏移量无效的情况下，消费者将从最新的记录开始读取数据（在消费者启动之后生成的记录）
      # earliest ：在偏移量无效的情况下，消费者将从起始位置读取分区的记录
      auto-offset-reset: earliest
      # 是否自动提交偏移量，默认值是true,为了避免出现重复数据和数据丢失，可以把它设置为false,然后手动提交偏移量
      enable-auto-commit: false
      # 键的反序列化方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 值的反序列化方式
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      # 在侦听器容器中运行的线程数。
      concurrency: 5
      #listner负责ack，每调用一次，就立即commit
      ack-mode: manual_immediate
      missing-topics-fatal: false

# 日志配置
logging:
  #  level:
  config: classpath:logback.xml

file:
  path: classpath:/file


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.hong.entity
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    default-executor-type: reuse
    default-statement-timeout: 25000

pullTask:
  # 是否开启数据同步
  pull: false
  behavior:
    scheduledCron: '*/5 * * * * ?'

executor:
  # 公共线程池核心线程数
  corePoolSize: 5
  # 公共线程池最大线程数
  maximumPoolSize: 10